[package]
name = "hl-arb-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
hex = "0.4.3"
reqwest = "0.12.25"
serde = {version = "1.0.228",features = ["derive"]}
serde_json = "1.0.145"
tokio = {version = "1.48.0",features = ["full"]}